"""Auto-generated fixtures — generated by TestForge."""
import pytest
import tempfile
import os
from pathlib import Path


@pytest.fixture
def temp_dir(tmp_path):
    """A temporary directory for file operations."""
    return tmp_path

@pytest.fixture
def sample_data():
    """Sample data dictionary for testing."""
    return {"name": "test", "value": 42, "items": [1, 2, 3]}

@pytest.fixture
def mock_env(monkeypatch):
    """Mock environment variables for testing."""
    monkeypatch.setenv("TEST_MODE", "true")
    monkeypatch.setenv("DB_HOST", "localhost")
